const BASE = 'https://api.spotify.com/v1'

function authHeaders(token) {
  return { Authorization: `Bearer ${token}` }
}

export async function getCurrentUser(token) {
  const res = await fetch(`${BASE}/me`, { headers: authHeaders(token) })
  return res.json()
}

export async function savePlaylist(token, userId, artistName, tourName, trackUris) {
  const createRes = await fetch(`${BASE}/users/${userId}/playlists`, {
    method: 'POST',
    headers: { ...authHeaders(token), 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: `${artistName} — ${tourName} Setlist`,
      description: `Predicted setlist for ${artistName}, generated by Setlist.`,
      public: true,
    }),
  })
  const playlist = await createRes.json()

  for (let i = 0; i < trackUris.length; i += 100) {
    await fetch(`${BASE}/playlists/${playlist.id}/tracks`, {
      method: 'POST',
      headers: { ...authHeaders(token), 'Content-Type': 'application/json' },
      body: JSON.stringify({ uris: trackUris.slice(i, i + 100) }),
    })
  }

  return playlist
}
